from typing import TypedDict, List, Dict

class AgentState(TypedDict):
    """
    Defines the shared state for the multi-agent system.
    This state stores data that agents read from and write to.
    """
    topic: str                          # Topic inputted by the user
    research_data: List[Dict[str, str]] # List of search results: [{"title": ..., "link": ..., "snippet": ...}]
    blog_post: str                      # Final blog post generated by the Writer Agent
