from typing import TypedDict

class AgentState(TypedDict):
    """
    Defines the shared state for the multi-agent system.
    This state stores data that agents read from and write to.
    """
    topic: str          # Topic inputted by the user
    research_data: str  # Research results collected by the Researcher Agent
    blog_post: str      # Final blog post generated by the Writer Agent
